years= (input("Enter Years"))
days= (input("Enter Days"))
hours= (input("Enter Hours"))
minutes= (input("Enter Minutes"))
seconds= (input("Enter Seconds"))
Total Seconds= (seconds+(minutes*60))
print("Total Seconds")