x=input("Enter Time in Seconds: ")
x=int(x)
Years=int((x//31536000)-=Days)
Days=int((x//86400)-=Hours)
Hours=int((x//3600)-=Minutes)
Minutes=int((x//60)-=Seconds)
Seconds=int(x//1)
#take total, divide by seconds in years/hours/days or whatever, then subtract from total and repeat for lesser values 
print(Years)
print(Days)
print(Hours)
print(Minutes)
print(Seconds)